name: haskell-api
version: '1.0.0'
category: Web
author: Danil Kaist
maintainer: kaystd@gmail.com
copyright: Danil Kaist
license: MIT
github: kaystd/haskell-api
extra-source-files:
  - README.md

default-extensions:
  - OverloadedStrings
  - DeriveGeneric

dependencies:
  - base
  - scotty
  - warp
  - bytestring
  - text
  - configurator
  - resource-pool
  - postgresql-simple
  - postgresql-simple-migration
  - aeson
  - transformers
  - MissingH
  - wai
  - wai-extra
  - http-types
  - base64-bytestring
  - jwt
  - containers
  - streaming-commons

executables:
  haskell-api-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N2
